---
- name: create symlinks
  file:
    src: "{{python_install_prefix}}/bin/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - { src: 'python2.7',        dest: 'python' }
    - { src: 'easy_install-2.7', dest: 'easy_install' }
    - { src: 'pip2.7',           dest: 'pip' }
    - { src: 'python2.7-config', dest: 'python-config' }
