---

- name: Include OS family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  become: true
  tags: python_install

- include: build.yml
  tags: python_build

- include: setuptools.yml
  tags: python_setuptools_build

- include: link.yml
  become: true
  tags: python_link

# vi:ts=2:sw=2:et:ft=yaml
