---

- name: Include OS family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include_tasks: "install/{{ansible_os_family}}.yml"
  become: true
  tags: python_install

- import_tasks: build.yml
  tags: python_build

- import_tasks: setuptools.yml
  tags: python_setuptools_build

- import_tasks: link.yml
  become: true
  tags: python_link

# vi:ts=2:sw=2:et:ft=yaml
