---

- name: Install pip
  become: yes
  easy_install: 
    name: "{{ item }}"
    state: latest
  with_items:
  - pip
  - virtualenv

- name: Install additional packages
  become: yes
  pip: 
    name: "{{ item }}"
    executable: /usr/local/bin/pip
  with_items:
  - "{{ python_modules }}"

# vi:ts=2:sw=2:et:ft=yaml
